class Error(Exception):
    pass


class ErrorAlreadyAttached(Error):
    pass
